name: CI - Build Backend

on:
  pull_request:
    branches:
      - main
      - master
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest # container
    services:
      postgres:
        image: postgres:15.4
        env:
          POSTGRES_USER: dk
          POSTGRES_PASSWORD: password
          POSTGRES_DB: customer
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4 # checkout branch
      - uses: actions/setup-java@v4 # setup java
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build and run Unit/Integration Test with Maven
        run: mvn -ntp -B verify